=== adrianmfuentes/nothingYouCareBout/xml/circuito.dtd
<!ELEMENT circuito (nombre, longitud_circuito, anchura_media, fecha_carrera_2024, hora_comienzo_Esp, 
    vueltas, ciudad, pais, referencias+,fotos+,videos+,centro-pista,puntos+)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT longitud_circuito (#PCDATA)>
 <!ELEMENT anchura_media (#PCDATA)>
<!ELEMENT fecha_carrera_2024 (#PCDATA)>
<!ELEMENT hora_comienzo_Esp (#PCDATA)>
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>

<!ELEMENT referencias EMPTY>
<!ELEMENT fotos EMPTY>
<!ELEMENT videos EMPTY>

<!ELEMENT centro-pista (coordenada)>
<!ELEMENT puntos (tramo+)>
<!ELEMENT tramo (coordenada+)>
<!ELEMENT coordenada (longitud, latitud, altitud)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>

<!ATTLIST referencias 
    enlace1 CDATA #REQUIRED
    enlace2 CDATA #REQUIRED 
    enlace3 CDATA #REQUIRED>

<!ATTLIST fotos 
    enlace1 CDATA #REQUIRED
    enlace2 CDATA #REQUIRED 
    enlace3 CDATA #REQUIRED>

<!ATTLIST videos 
    enlace1 CDATA #REQUIRED
    enlace2 CDATA #REQUIRED 
    enlace3 CDATA #REQUIRED>

<!ATTLIST tramo 
    distancia CDATA #REQUIRED
    sector CDATA #REQUIRED>

=== adrianmfuentes/nothingYouCareBout/xml/circuito.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE circuito SYSTEM "./circuito.dtd">

<circuito>
    <nombre>Zandvoort</nombre>
    <longitud_circuito>4259m</longitud_circuito>
    <anchura_media>11m</anchura_media>
    <fecha_carrera_2024>2024-08-25</fecha_carrera_2024>
    <hora_comienzo_Esp>15:00:00</hora_comienzo_Esp>
    <vueltas>72</vueltas>
    <ciudad>Zandvoort</ciudad>
    <pais>Pa√≠ses Bajos</pais>

    <referencias
        enlace1="https://www.circuitzandvoort.nl/"
        enlace2="https://www.formula1.com/en/racing/2024/netherlands"
        enlace3="https://www.redbull.com/mx-es/f1-circuito-zandvoort-lo-que-debes-saber" />

    <fotos
        enlace1="../multimedia/imagenes/zandvoort-1.jpg"
        enlace2="../multimedia/imagenes/zandvoort-2.jpg"
        enlace3="../multimedia/imagenes/zandvoort-3.jpg" />

    <videos
        enlace1="../multimedia/videos/zandvoort-2024-pole.mp4"
        enlace2="../multimedia/videos/zandvoort-verstappen-lap.mp4"
        enlace3="../multimedia/videos/zandvoort-drone.mp4" />

    <centro-pista>
        <coordenada>
            <longitud>4.5408</longitud>
            <latitud>52.3889</latitud>
            <altitud>17.84</altitud>
        </coordenada>
    </centro-pista>

    <puntos>
        <!-- SECTOR 1 -->
        <tramo distancia="380.72" sector="1">
            <coordenada>
                <longitud>4.540872083168406</longitud>
                <latitud>52.3889895470644</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="72.31" sector="1">
            <coordenada>
                <longitud>4.54287479354698</longitud>
                <latitud>52.39177538820797</latitud>
                <altitud>20</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="29.15" sector="1">
            <coordenada>
                <longitud>4.54352499654938</longitud>
                <latitud>52.39176547354719</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="24.29" sector="1">
            <coordenada>
                <longitud>4.543746618459663</longitud>
                <latitud>52.39162494540162</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="55.71" sector="1">
            <coordenada>
                <longitud>4.543788294092588</longitud>
                <latitud>52.39140985677778</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="149.80" sector="1">
            <coordenada>
                <longitud>4.543533741243109</longitud>
                <latitud>52.39097692756786</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="50.50" sector="1">
            <coordenada>
                <longitud>4.543533741243109</longitud>
                <latitud>52.39097692756786</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="20.80" sector="1">
            <coordenada>
                <longitud>4.542898238220204</longitud>
                <latitud>52.3897852862364</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="22.27" sector="1">
            <coordenada>
                <longitud>4.542890920021216</longitud>
                <latitud>52.38932979651433</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="26.66" sector="1">
            <coordenada>
                <longitud>4.542833599042792</longitud>
                <latitud>52.38915112907024</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="106.61" sector="1">
            <coordenada>
                <longitud>4.542677571135119</longitud>
                <latitud>52.38902519072091</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="25.85" sector="1">
            <coordenada>
                <longitud>4.542453900784238</longitud>
                <latitud>52.38893846522145</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="19.55" sector="1">
            <coordenada>
                <longitud>4.541518647873621</longitud>
                <latitud>52.38872665058949</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="19.22" sector="1">
            <coordenada>
                <longitud>4.541321436121333</longitud>
                <latitud>52.38860321134414</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="28.28" sector="1">
            <coordenada>
                <longitud>4.541253669995282</longitud>
                <latitud>52.38844049877736</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="25.16" sector="1">
            <coordenada>
                <longitud>4.541318788969355</longitud>
                <latitud>52.38827984142112</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="57.00" sector="1">
            <coordenada>
                <longitud>4.541543607654564</longitud>
                <latitud>52.38816051522823</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="60.22" sector="1">
            <coordenada>
                <longitud>4.541766397501834</longitud>
                <latitud>52.38812069246169</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="74.66" sector="1">
            <coordenada>
                <longitud>4.542272723848304</longitud>
                <latitud>52.38820110993746</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="86.82" sector="1">
            <coordenada>
                <longitud>4.542802777973596</longitud>
                <latitud>52.38831265471125</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="67.36" sector="1">
            <coordenada>
                <longitud>4.543464229317992</longitud>
                <latitud>52.38842812726368</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="105.35" sector="1">
            <coordenada>
                <longitud>4.544243111882698</longitud>
                <latitud>52.38848324378812</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="101.61" sector="1">
            <coordenada>
                <longitud>4.544848474916218</longitud>
                <latitud>52.3884606169007</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="67.59" sector="1">
            <coordenada>
                <longitud>4.545789688801269</longitud>
                <latitud>52.38835185782398</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="51.97" sector="1">
            <coordenada>
                <longitud>4.546699375657532</longitud>
                <latitud>52.3882652029383</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="52.19" sector="1">
            <coordenada>
                <longitud>4.54730481056528</longitud>
                <latitud>52.38831982393668</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="125.46" sector="1">
            <coordenada>
                <longitud>4.547759000050702</longitud>
                <latitud>52.3884305693687</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="55.37" sector="1">
            <coordenada>
                <longitud>4.548194588705467</longitud>
                <latitud>52.38860581009058</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="69.66" sector="1">
            <coordenada>
                <longitud>4.548194588705467</longitud>
                <latitud>52.38860581009058</latitud>
                <altitud>18</altitud>
            </coordenada>
        </tramo>
        
               

        <!-- SECTOR 2 -->
        <tramo distancia="81.83" sector="2">
            <coordenada>
                <longitud>4.549277052699168</longitud>
                <latitud>52.38892517576789</latitud>
                <altitud>23</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="47.55" sector="2">
            <coordenada>
                <longitud>4.549772757965503</longitud>
                <latitud>52.3889726527162</latitud>
                <altitud>23</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="40.07" sector="2">
            <coordenada>
                <longitud>4.550399139147466</longitud>
                <latitud>52.38896323618066</latitud>
                <altitud>22</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="35.10" sector="2">
            <coordenada>
                <longitud>4.55100079294221</longitud>
                <latitud>52.38894248908786</latitud>
                <altitud>20</altitud>
            </coordenada>
        </tramo>
        <tramo distancia="30.31" sector="2">
            <coordenada>
                <longitud>4.55173585482717</longitud>
